[package]
name = "physics"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.20.2"
miniquad = { version = "=0.3.0-alpha.42", features = ["log-impl"] }
quad-rand = "0.2.1"